// Google Apps Script for surveyframe response collection
// Generated by surveyframe (export_google_sheet() or the SurveyBuilder)
// Target Google Sheet: container-bound: paste into your new sheet, URL not required
//
// Setup:
// 1. Open the target Google Sheet
// 2. Go to Extensions > Apps Script
// 3. Paste this entire file, replacing any existing code
// 4. Click Deploy > New deployment > Web app
// 5. Set "Who has access" to "Anyone"
// 6. Copy the Web App URL and paste it into the SurveyBuilder
//    under Survey > Google Sheets Setup

const SHEET_NAME = "Responses";
const TARGET_SHEET_URL = "container-bound: paste into your new sheet, URL not required";
const EXPECTED_COLUMNS = ["respondent_id","started_at","submitted_at","elig_age","elig_nationality","elig_resort_stay","elig_stay_duration","elig_room_service","elig_rs_times","elig_smartphone","prof_mode_first","prof_tried_other","prof_app_frequency","prof_chatbot_prior","prof_age_group","prof_gender","aia_1","aia_2","aia_3","aia_4","poa_1","poa_2","poa_3","poa_4","peou_1","peou_2","peou_3","peou_4","pu_1","pu_2","pu_3","pu_4","pr_1","pr_2","pr_3","pr_4","bi_1","bi_2","bi_3","bi_4","fe_1","fe_2","fe_3","fe_4","fe_5","fe_6","od_1","od_2"];
const MAX_BODY_CHARS = 200000;

function doPost(e) {
  try {
    if (!e || !e.postData || !e.postData.contents) {
      throw new Error("Missing POST body.");
    }
    if (e.postData.contents.length > MAX_BODY_CHARS) {
      throw new Error("POST body too large.");
    }
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    let sheet = ss.getSheetByName(SHEET_NAME);

    if (!sheet) {
      sheet = ss.insertSheet(SHEET_NAME);
      sheet.appendRow(EXPECTED_COLUMNS);
      sheet.getRange(1, 1, 1, EXPECTED_COLUMNS.length)
           .setFontWeight("bold")
           .setBackground("#1a1a2e")
           .setFontColor("#ffffff");
    }

    const data = JSON.parse(e.postData.contents);
    if (!data || Array.isArray(data) || typeof data !== "object") {
      throw new Error("POST body must be a JSON object.");
    }
    const row = EXPECTED_COLUMNS.map(col => data[col] !== undefined ? data[col] : "");
    sheet.appendRow(row);

    return ContentService
      .createTextOutput(JSON.stringify({ status: "ok", rows: sheet.getLastRow() - 1 }))
      .setMimeType(ContentService.MimeType.JSON);

  } catch (err) {
    return ContentService
      .createTextOutput(JSON.stringify({ status: "error", message: err.toString() }))
      .setMimeType(ContentService.MimeType.JSON);
  }
}

function doGet(e) {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName(SHEET_NAME);
  if (!sheet) {
    return ContentService
      .createTextOutput(JSON.stringify({ status: "ok", rows: 0 }))
      .setMimeType(ContentService.MimeType.JSON);
  }
  const lastRow = sheet.getLastRow();
  return ContentService
    .createTextOutput(JSON.stringify({ status: "ok", rows: Math.max(0, lastRow - 1) }))
    .setMimeType(ContentService.MimeType.JSON);
}
